### PR TITLE
Added functionality for filtering on SEN courses

### PR DESCRIPTION
**Pull request by MartinBentley**
### Context
There is a requirement to find courses with special education needs. Here is the card:
https://trello.com/c/dehAp9dq/574-search-by-send-courses

### Changes proposed in this pull request
A new flag has been added to the results filter.

### CODE REVIEW

**Comment by dankmitchell** [comment]
Agree with Sau

**Comment by fofr** [comment]
It was my suggestion that we _also_ look for SEN in titles as there's prior art for a subject based on text occuring in the title here: https://github.com/DFE-Digital/manage-courses-api/blob/e2266fb71484b8b3a3ad96ccd0782301e48a5718/src/ManageCourses.Api/Mapping/SubjectMapper.cs#L119-L124

I think a course should be considered SEN if any of these are true:
* Special Educational Needs UCAS subject
* SEN, SEND or Special Educational Needs in the title

**Comment by benilovj** [comment]
@fofr fair enough, your suggestion will work too - let’s go with this.

**Comment by dankmitchell** [comment]
I don’t think we should be making the decision if a course if SEN based on its title. If the provider hasn’t marked it as SEN in UCAS then it’s a data issue that should be corrected at the source.

**Comment by defong** [comment]
[Search by SEND courses](https://trello.com/c/dehAp9dq/574-search-by-send-courses)

**Pull request merged**
