### PR TITLE
Use vac status

### PR DESCRIPTION
**Pull request by MartinBentley**
### Context
There is a requirement to pull vac status into search and compare.
Here is the PR: https://trello.com/c/uRcCqSlF/485-publish-per-course-vacancy-info-to-search
This pr creates the new db fields

### CODE REVIEW

**Comment by timabell** [comment]
I don't think it matters too much as this is all read-only data shipped across from manage courses which does the actual calculation

**Comment by benilovj** [comment]
Every instance where we couple our logic to the existing UCAS data model is another place where we have to unpick it when that model will change and another potential source for bugs.

**Comment by defong** [comment]
@MartinBentley I marking this as wip until its decided.

and here's my 2 pence

A course has vacancies, the vacancies is a sum of vacancies in a campus. A campus vacancies cannot be over subscribed (ie, max classroom size)

**Comment by benilovj** [comment]
@MartinBentley @defong @timabell after discussion, I've removed my objections and this PR is ready for a review, I've removed the WIP tag.

**Pull request merged**
